export const endpoints_properties =
  {
    "ENDPOINT_IDENTITY_LOCAL" : "http://localhost:4728",
    "ENDPOINT_PERSONAL_DETAILS_LOCAL" : "http://localhost:4753",
    "ENDPOINT_RECOMMENDED_SERVICES_LOCAL" : "http://localhost:4755",
    "ENDPOINT_SKILLS_LOCAL" : "http://localhost:4744",
    "ENDPOINT_SERVICE_APPLICATIONS_LOCAL" : "http://localhost:4740",
    "ENDPOINT_SC_SERVICES_LOCAL": "http://localhost:4726",
    "ENDPOINT_INDUSTRIES_LOCAL" :"http://localhost:4719",
    "ENDPOINT_COMPANIES_LOCAL" : "http://localhost:4707",
    "ENDPOINT_SERVICE_TITLES_LOCAL" : "http://localhost:4727",
    "ENDPOINT_COUNTRIES_LOCAL":"http://localhost:4711",
    "ENDPOINT_CITIES_LOCAL":"http://localhost:4706",
    "ENDPOINT_DEGREES_LOCAL" : "http://localhost:4702",
    "ENDPOINT_INSTITUTES_LOCAL": "http://localhost:4721",
    "ENDPOINT_LANGUAGES_LOCAL" :"http://localhost:4729",
    "ENDPOINT_CURRENCIES_LOCAL" : "http://localhost:4767",
    "ENDPOINT_SEARCH_SERVICES_LOCAL" : "http://localhost:4739",
    "ENDPOINT_USER_EDUCATIONS_LOCAL": "http://localhost:4757",
    "ENDPOINT_SC_REQUIRED_LANGUAGES_LOCAL": "http://localhost:4764",
    "ENDPOINT_USER_PROJECTS_LOCAL": "http://localhost:4758",
    "ENDPOINT_PROFILE_VIEWER_LOCAL": "http://localhost:4734",
    "ENDPOINT_USER_RESUME_DOWNLOAD" : "http://localhost:4716",
    "ENDPOINT_USER_RESUME_UPLOAD": "http://localhost:4717",
    "ENDPOINT_SC_REQUIRED_SKILLS_LOCAL": "http://localhost:4713",
    "ENDPOINT_NATIONALITIES_LOCAL" : "http://localhost:4763",
    "ENDPOINT_FIELD_OF_RECRUITMENT_LOCAL" : "http://localhost:4715",
    "ENDPOINT_DEV" :"https://6kmxdtde21.execute-api.ap-south-1.amazonaws.com/dev",
    "ENDPOINT_PROD" : "https://ub61wtkdyl.execute-api.ap-south-1.amazonaws.com/prod",
  }